[package]
name = "backup-checker"
version = "0.2.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.29", features = ["derive"] }
sha256 = "1.5.0"
indicatif = {version = "*", features = ["rayon"]}
rayon = "1.10.0"
owo-colors = "4"
