[package]
name = "backup-checker"
version = "0.1.2"
edition = "2021"

[dependencies]
clap = { version = "4.5.21", features = ["derive"] }
log = "0.4.22"
sha256 = "1.5.0"
indicatif = {version = "*", features = ["rayon"]}
rayon = "1.10.0"